version: '2'
services:
  web:
    build: .
    ports:
      - "7000:7000"
    links:
      - 'rethinkdb'
    environment:
      - RETHINKDB=rethinkdb
      - PORT=7000
  rethinkdb:
    image: rethinkdb
    ports:
        - "8080"
        - "28015"
        - "29015"
