version: '2'
services:
  web:
    build: .
    ports:
      - "7000:7000"
    links:
      - 'rethinkdb'
    environment:
      - RETHINKDB=rethinkdb
      - PORT=7000
  docs:
    build: 
      context: git@github.com:Runnable/docs.git
    ports:
      - "7000:7000"
